import type { Lang } from "./";

export const text = {
  en: {
    shareX: "Share on X",
    copyText: "Copy text",
    copied: "Copied!",
    copyFailed: "Could not copy automatically. Select and copy the text below.",
    round: "Round",
    target: "Object",
    error: "Angular error",
    score: "Points",
    complete: "Expedition complete",
    playAgain: "Play again",
    result: "Round result",
    yourGuess: "Your guess",
    answer: "Actual position",
    viewResults: "View results",
    next: "Next object",
    selected: "Position selected. Ready to lock it in?",
    placeGuess: "Tap the sky to place your guess.",
    controls: "Drag to explore · Scroll or pinch to zoom",
    submit: "Lock in guess",
    rules:
      "Five objects. One sky. Find each object and earn up to 5,000 points per round. Closer guesses score higher.",
    catalogue: "A starter collection of 12 Messier objects.",
    hintDescription: "Constellation lines and a constellation clue.",
    noHintDescription: "Just the stars and your knowledge of the sky.",
    title: "StarGuessr",
    description:
      "Guess the position of stars and deep-sky objects on the celestial sphere.",
    noHint: "No Hint",
    hint: "Hint",
    start: "Start",
    backToMenu: "Back to Menu",
  },
  ja: {
    shareX: "Xでシェア",
    copyText: "テキストをコピー",
    copied: "コピーしました！",
    copyFailed:
      "自動コピーできませんでした。下のテキストを選択してコピーしてください。",
    round: "ラウンド",
    target: "天体",
    error: "角距離",
    score: "スコア",
    complete: "探索完了",
    playAgain: "もう一度プレイ",
    result: "ラウンド結果",
    yourGuess: "あなたの予想",
    answer: "正しい位置",
    viewResults: "結果を見る",
    next: "次の天体",
    selected: "位置を選択しました。予想を確定しましょう。",
    placeGuess: "星空をタップして位置を予想してください。",
    controls: "ドラッグで見回す · スクロールやピンチで拡大",
    submit: "予想を確定",
    rules:
      "5つの天体を探しましょう。正解に近いほど高得点。各ラウンド最大5,000点です。",
    catalogue: "12個のメシエ天体から出題します。",
    hintDescription: "星座線と星座名を手がかりに探索。",
    noHintDescription: "星空の知識だけで挑戦。",
    title: "StarGuessr",
    description: "星や天体の位置を当てよう。",
    noHint: "ノーヒント",
    hint: "ヒントあり",
    start: "スタート",
    backToMenu: "メニューに戻る",
  },
} satisfies Record<Lang, Record<string, string>>;
